### ISSUE TITLE
Create View for event creation

### ISSUE THREAD

**Issue by Curtis-Barnhart** [mikeryu/westmont-cs130-f23-team-gold#13]
# User Story
1. I as a user should be able to navigate to a page where I will later be able to make new events.
2. I as a user should be able to access the event creation page from my user dashboard.

# Implementation
A new View needs to be made in the app for creating event flows.
A button should be added anywhere on the user dashboard which will redirect the user to the event creation page.
This will involve making the view and creating a template for it (which can be blank for now), as well as sorting out the url mappings.

**Comment by benyeom** [comment]
wireframe: https://app.diagrams.net/#G1wLamU1hBixgmv4mqV8fSRMju3we8pJhO
