### ISSUE TITLE
view event details

### ISSUE THREAD

**Issue by mnugent04** [mikeryu/westmont-cs130-f23-team-gold#46]
New html page that allows the user to click on a specific event and access all the details of event

**Comment by mnugent04** [comment]
![Image](https://github.com/mikeryu/westmont-cs130-f23-team-gold/assets/143567359/96157570-6264-4b96-901c-cc2e84abc4cb)

**Comment by zablon-oigo** [comment]
> New html page that allows the user to click on a specific event and access all the details of event

hello, I would like to give it a try

**Comment by LoganTown** [comment]
I am currently working on this issue

**Comment by Curtis-Barnhart** [comment]
Logan can you link this to a pr?
